"""ABOUTME: Pre-defined fill pattern templates for Tambor drum machine.
ABOUTME: Contains 16 musically-interesting fill variations that can be assigned to patterns."""

def expand_fill_to_steps(fill_pattern: list, target_steps: int) -> list:
    """Expand a 16-step fill template to match the current pattern's step count.

    Args:
        fill_pattern: Fill pattern with 8 drums × 16 steps
        target_steps: Target step count (2-32)

    Returns:
        Expanded fill pattern with 8 drums × target_steps
    """
    if target_steps == 16:
        return fill_pattern  # No expansion needed

    target_steps = max(2, min(32, target_steps))  # Clamp to valid range
    expanded = []

    for drum_idx, drum_pattern in enumerate(fill_pattern):
        if target_steps <= 16:
            # Shrink: take first N steps
            expanded_drum = drum_pattern[:target_steps]
        else:
            # Expand: repeat pattern to fill target steps
            expanded_drum = []
            for step_idx in range(target_steps):
                # Map step to 16-step cycle (with repetition for 32 steps, etc.)
                source_step = (step_idx * 16) // target_steps
                source_step = min(source_step, 15)  # Clamp to 0-15
                expanded_drum.append(drum_pattern[source_step].copy())

        expanded.append(expanded_drum)

    return expanded


# 16 pre-defined fill templates
# Each fill is a pattern of 8 drums × 16 steps
# Format matches regular pattern structure: [drum_idx][step] = {"active": bool, "velocity": int, "note_length": float}
# Fills are expanded dynamically to match current pattern's step count

FILL_TEMPLATES = {
    1: {
        "name": "Fill Kick Build",
        "description": "Kick intensity builds, snare steady",
        "pattern": [
            # Kick - plays on every step, building
            [
                {"active": True, "velocity": 80, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 85, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 90, "note_length": 0.5},
                {"active": True, "velocity": 90, "note_length": 0.5},
                {"active": True, "velocity": 95, "note_length": 0.5},
                {"active": True, "velocity": 95, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": True, "velocity": 115, "note_length": 0.5},
                {"active": True, "velocity": 120, "note_length": 0.5},
            ],
            # Snare - steady on 2 & 4
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Closed HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Open HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Clap - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Hi - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Mid - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Low - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
        ]
    },

    2: {
        "name": "Fill Snare Roll",
        "description": "Snare roll builds, kick steady",
        "pattern": [
            # Kick - steady 4-on-floor
            [
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Snare - builds to roll
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 90, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 95, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": True, "velocity": 115, "note_length": 0.5},
                {"active": True, "velocity": 120, "note_length": 0.5},
            ],
            # Closed HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Open HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Clap - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Hi - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Mid - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Low - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
        ]
    },

    3: {
        "name": "Fill Tom Ascend",
        "description": "Tom fill ascending Hi→Mid→Low",
        "pattern": [
            # Kick - steady
            [
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Snare - on 2 & 4
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Closed HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Open HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Clap - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Hi - ascending fill starts
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Mid - continues fill
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
            ],
            # Tom Low - finishes fill
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
        ]
    },

    4: {
        "name": "Fill Kick Snare Combo",
        "description": "Kick and snare syncopation",
        "pattern": [
            # Kick - syncopated
            [
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": True, "velocity": 115, "note_length": 0.5},
            ],
            # Snare - syncopated counterpoint
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": True, "velocity": 120, "note_length": 0.5},
            ],
            # Closed HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Open HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Clap - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Hi - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Mid - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Low - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
        ]
    },

    5: {
        "name": "Fill HH Swell",
        "description": "Hi-hat intensity builds",
        "pattern": [
            # Kick - steady
            [
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Snare - 2 & 4
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Closed HH - builds
            [
                {"active": True, "velocity": 80, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 80, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 85, "note_length": 0.5},
                {"active": True, "velocity": 85, "note_length": 0.5},
                {"active": True, "velocity": 90, "note_length": 0.5},
                {"active": True, "velocity": 90, "note_length": 0.5},
                {"active": True, "velocity": 95, "note_length": 0.5},
                {"active": True, "velocity": 95, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": True, "velocity": 115, "note_length": 0.5},
            ],
            # Open HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Clap - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Hi - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Mid - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Low - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
        ]
    },

    6: {
        "name": "Fill Minimal",
        "description": "Sparse, syncopated fill",
        "pattern": [
            # Kick - syncopated hits
            [
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
            ],
            # Snare - just on 2 & 4
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Closed HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Open HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Clap - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Hi - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Mid - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Low - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
        ]
    },

    7: {
        "name": "Fill Double Time",
        "description": "Fast double-time kick pattern",
        "pattern": [
            # Kick - double time
            [
                {"active": True, "velocity": 95, "note_length": 0.5},
                {"active": True, "velocity": 90, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 95, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": True, "velocity": 115, "note_length": 0.5},
                {"active": True, "velocity": 120, "note_length": 0.5},
            ],
            # Snare - 2 & 4
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 105, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": True, "velocity": 110, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Closed HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Open HH - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Clap - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Hi - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Mid - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
            # Tom Low - empty
            [
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
                {"active": False, "velocity": 100, "note_length": 0.5},
            ],
        ]
    },
}


def get_fill_template(fill_id: int) -> dict:
    """Get a fill template by ID."""
    return FILL_TEMPLATES.get(fill_id)


def get_all_fill_ids() -> list:
    """Get list of all available fill IDs."""
    return sorted(list(FILL_TEMPLATES.keys()))


def get_fill_names() -> dict:
    """Get mapping of fill IDs to names and descriptions."""
    return {
        fill_id: {
            "name": data["name"],
            "description": data["description"]
        }
        for fill_id, data in FILL_TEMPLATES.items()
    }
